apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: obokk885/springboot-k8s-example:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred


---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJvYm9razg4NSIsInBhc3N3b3JkIjoiUUlGZ2pndGI0NTFkYnZqdGtmIiwiZW1haWwiOiJsZWFybmluZy5vYm9ra0BnbWFpbC5jb20iLCJhdXRoIjoiYjJKdmEyczRPRFU2VVVsR1oycG5kR0kwTlRGa1luWnFkR3RtIn19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-svc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort